apiVersion: v2
name: kubeflow
description: Kubeflow - Machine Learning Toolkit for Kubernetes
type: application
version: 1.10.0
appVersion: 1.10.0
home: https://www.kubeflow.org/
sources:
- https://github.com/kubeflow/manifests
keywords:
- kubeflow
- machine-learning
- ml
- ai
- kubernetes
- mlpipeline
- katib
- kserve
maintainers:
- name: Kubeflow Team
  email: kubeflow-discuss@googlegroups.com
annotations:
  kustomize.commit: 46f3142
  kustomize.branch: master
  kustomize.commitDate: 2026-03-27 08:50:50 +0000
  helm.generatedAt: '2026-04-07T19:13:44.008105'
